# Generated by Django 3.2.6 on 2021-08-13 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0002_user_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='publish',
            field=models.BooleanField(default=True),
        ),
    ]
